---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Jenkins pipeline
    tags: jenkins, pipeline
  name: pipeline-template
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "devops", "kind": "DeploymentConfig"}]'
      labels:
        app: cicd-pipeline
        name: cicd-pipeline
      name: "${NAME}-pipeline"
    spec:
      triggers:
        - type: GitHub
          github:
            secret: ${WEBHOOK_SECRET}
        - type: Generic
          generic:
            secret: ${WEBHOOK_SECRET}
      runPolicy: Serial
      source:
        git:
          uri: https://github.com/andrexbass/ocp-cicd
      strategy:
        jenkinsPipelineStrategy:
          type: JenkinsPipeline
          jenkinsfilePath: Jenkinsfile
          env:
          - name: url
            value: ${URL}
parameters:
- displayName: Nome da aplicacao
  name: NAME
  required: true
  value: app
- displayName: URL do repositorio git
  name: URL
  required: true
          
            